services:

  bank-notification-db:
    image: postgres:16
    container_name: notification-db
    environment:
      POSTGRES_DB: notifications
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5436:5432"
