apiVersion: v1
kind: Endpoints
metadata:
  name: {{ .Values.service.name | default "keycloak" }}
  namespace: {{ .Release.Namespace }}
subsets:
  - addresses:
      - ip: {{ .Values.externalIP }}
    ports:
      - port: {{ .Values.service.port | default 9002 }}
        protocol: TCP