apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name | default "keycloak" }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.service.name | default "keycloak" }}
    component: external
spec:
  ports:
    - port: {{ .Values.service.port | default 9002 }}
      targetPort: {{ .Values.service.targetPort | default 9002 }}
      protocol: TCP