services:
#  keycloak:
#    image: quay.io/keycloak/keycloak:24.0
#    container_name: bank-keycloak
#    command: start-dev # --import-realm
#    environment:
#      KEYCLOAK_ADMIN: admin
#      KEYCLOAK_ADMIN_PASSWORD: admin
#    ports:
#      - "9092:8080"
#    volumes:
#      - ./keycloak:/opt/keycloak/data/import
#    healthcheck:
#      test: [ "CMD", "curl", "-f", "http://localhost:9092/health/ready" ]
#      interval: 10s
#      timeout: 10s
#      retries: 5

  account-service:
    build:
      context: ./account-service
      dockerfile: Dockerfile
    ports:
      - "${ACCOUNT_SERVER_PORT}:${ACCOUNT_SERVER_PORT}"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://${ACCOUNT_DB_HOST}:5432/${ACCOUNT_DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${ACCOUNT_DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${ACCOUNT_DB_PASSWORD}
      SERVER_PORT: ${ACCOUNT_SERVER_PORT}
    depends_on:
      - account-db

  account-db:
    image: postgres:16
    container_name: account-db
    environment:
      POSTGRES_DB: ${ACCOUNT_DB_NAME}
      POSTGRES_USER: ${ACCOUNT_DB_USERNAME}
      POSTGRES_PASSWORD: ${ACCOUNT_DB_PASSWORD}
    ports:
      - "5433:5432"
#
#  order-service:
#    build:
#      context: ./order-application
#      dockerfile: Dockerfile
#    ports:
#      - "${ORDER_SERVICE_PORT}:${ORDER_SERVICE_PORT}"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://${ORDER_DB_HOST}:5432/${ORDER_DB_NAME}
#      SPRING_DATASOURCE_USERNAME: ${ORDER_DB_USERNAME}
#      SPRING_DATASOURCE_PASSWORD: ${ORDER_DB_PASSWORD}
#      SERVER_PORT: ${ORDER_SERVICE_PORT}
#
#      # Конфигурация user-client
#      USER_CLIENT_BASE_URL: ${USER_CLIENT_BASE_URL}
#    depends_on:
#      - order-db
#
#  order-db:
#    image: postgres:16
#    container_name: order-db
#    environment:
#      POSTGRES_DB: ${ORDER_DB_NAME}
#      POSTGRES_USER: ${ORDER_DB_USERNAME}
#      POSTGRES_PASSWORD: ${ORDER_DB_PASSWORD}
#    ports:
#      - "5434:5432"
