server:
  port: 9001

spring:
  application:
    name: gateway

  main:
    web-application-type: reactive

  # TODO remove
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.reactive.ReactiveSecurityAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.security.reactive.ReactiveManagementWebSecurityAutoConfiguration


#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          # Адрес issuer (Keycloak realm). Gateway по нему получает ключи
#          # и параметры токена, чтобы валидировать JWT от UI
#          issuer-uri: http://localhost:9002/realms/bank-realm

  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        instance-id: ${spring.application.name}:${random.value}
        prefer-ip-address: true
        service-name: ${spring.application.name}
        health-check-path: /actuator/health
        health-check-interval: 10s
    gateway:
      routes:
        - id: account-service-route
          uri: lb://account-service
          predicates:
            - Path=/account/**
#          TODO: uncomment
#          filters:
#            - name: TokenRelay

        - id: cash-service-route
          uri: lb://cash-service
          predicates:
            - Path=/cash/**
#          TODO: uncomment
#          filters:
#            - name: TokenRelay

        - id: transfer-service-route
          uri: lb://transfer-service
          predicates:
            - Path=/transfer/**
#          TODO: uncomment
#          filters:
#            - name: TokenRelay

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.gateway: DEBUG