server:
  port: 9000

spring:
  application:
    name: front-ui

# TODO remove
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration

gateway:
  url: http://localhost:9001

#transfer:
#  service:
#    url: ${GATEWAY_URL:http://localhost:9001}
#
#cash:
#  service:
#    url: ${GATEWAY_URL:http://localhost:9001}
#
#account:
#  service:
#    url: ${GATEWAY_URL:http://localhost:9001}

#  security:
#    oauth2:
#      client:
#        registration:
#          # Регистрация для пользователей (Authorization Code Flow)
#          keycloak:
#            client-id: front-ui
#            client-secret: NX8yUnStU5VmdmRvItT57vKA9UDKL2Lh
#            authorization-grant-type: authorization_code
#            scope: openid, profile
#            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
#            provider: keycloak
#        provider:
#          keycloak:
#            issuer-uri: http://localhost:9002/realms/bank-realm

feign:
  httpclient:
    enabled: true