server:
  port: ${CASH_SERVER_PORT:9003}

spring:
  application:
    name: transfer-service

  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      discovery:
        instance-id: ${spring.application.name}:${random.value}
        prefer-ip-address: true
        service-name: ${spring.application.name}
        health-check-path: /actuator/health
        health-check-interval: 10s
    gateway:
      routes:
        - id: account-service-route
          uri: lb://account-service
          predicates:
            - Path=/account/**
        #          TODO: uncomment
        #          filters:
        #            - name: TokenRelay

        - id: notification-service-route
          uri: lb://notification-service
          predicates:
            - Path=/notification/**
        #          TODO: uncomment
        #          filters:
        #            - name: TokenRelay

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/transfers}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:9002/realms/bank-realm}
#      client:
#        registration:
#          transfer-service:
#            provider: keycloak
#            client-id: transfer-service
#            client-secret: D68a7ktWHTKeZIwQRwTI0FrpJLZzq3AK
#            authorization-grant-type: client_credentials
#        provider:
#          keycloak:
#            issuer-uri: http://localhost:9002/realms/bank-realm

feign:
  httpclient:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always