server:
  port: ${SERVER_PORT:9005}

spring:
  application:
    name: account-service

  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      discovery:
        instance-id: ${spring.application.name}:${random.value}
        prefer-ip-address: true
        service-name: ${spring.application.name}
        health-check-path: /actuator/health
        health-check-interval: 10s
    gateway:
      routes:
        - id: notification-service-route
          uri: lb://notification-service
          predicates:
            - Path=/notification/**
        #          TODO: uncomment
        #          filters:
        #            - name: TokenRelay

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/accounts}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:9002/realms/bank-realm}

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always