  {{- if .Values.kafka.topics.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-kafka-topics-config
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
data:
  topics.yaml: |
    topics:
      {{- range .Values.kafka.topics.list }}
      - name: {{ .name | quote }}
        partitions: {{ .partitions | default 1 }}
        replicationFactor: {{ .replicationFactor | default 1 }}
        config: {{ .config | default "" | quote }}
      {{- end }}
  {{- end }}
