input {
  kafka {
    bootstrap_servers => "bank-kafka:9092"
    topics => ["bank-logs"]
    group_id => "bank-group"
  }
}

filter {
  mutate {
    copy => { "[@metadata][kafka][topic]" => "source"}
  }
}

output {
  stdout {
  }
  elasticsearch {
    hosts => ["http://bank-elasticsearch:9200"]
    index => "bank-logs-%{+dd.MM.YYYY}"
  }
}



