apiVersion: v2
name: helm
description: A Umbrella chart for deploying Bank platform microservices
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  # Subchart for External Keycloak
  - name: keycloak-external
    version: 0.1.0
    condition: keycloak-external.enabled

  # Subchart for Account Service
  - name: account-service
    version: "0.1.0"
    repository: "file://./charts/account-service" # Local path reference

  # Subchart for Cash Service
  - name: cash-service
    version: "0.1.0"
    repository: "file://./charts/cash-service"  # Local path reference

  # Subchart for Transfer Service
  - name: transfer-service
    version: "0.1.0"
    repository: "file://./charts/transfer-service"  # Local path reference

  # Subchart for Notification Service
  - name: notification-service
    version: "0.1.0"
    repository: "file://./charts/notification-service"  # Local path reference

  # Dependency for Account DB (e.g., PostgreSQL)
  - name: postgresql
    version: "18.2.0" # Using a specific known stable version from Bitnami history
    repository: "oci://registry-1.docker.io/bitnamicharts"
    alias: account-db # Alias to distinguish this instance
    condition: account-db.enabled # Allow disabling if needed

  # Dependency for Cash DB (e.g., PostgreSQL)
  - name: postgresql
    version: "18.2.0" # Using a specific known stable version from Bitnami history
    repository: "oci://registry-1.docker.io/bitnamicharts"
    alias: cash-db # Alias to distinguish this instance
    condition: cash-db.enabled # Allow disabling if needed

  # Dependency for Transfer DB (e.g., PostgreSQL)
  - name: postgresql
    version: "18.2.0" # Using a specific known stable version from Bitnami history
    repository: "oci://registry-1.docker.io/bitnamicharts"
    alias: transfer-db # Alias to distinguish this instance
    condition: transfer-db.enabled # Allow disabling if needed

  # Dependency for Notification DB (e.g., PostgreSQL)
  - name: postgresql
    version: "18.2.0" # Using a specific known stable version from Bitnami history
    repository: "oci://registry-1.docker.io/bitnamicharts"
    alias: notification-db # Alias to distinguish this instance
    condition: notification-db.enabled # Allow disabling if needed

  - name: kafka
    version: "25.0.0"
    repository: "oci://registry-1.docker.io/bitnamicharts"
    condition: kafka.enabled
