apiVersion: v2
name: helm
description: A Umbrella chart for deploying Bank platform microservices
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:

  - name: keycloak-external
    version: "0.1.0"
    condition: keycloak-external.enabled

  - name: account-service
    version: "0.1.0"
    repository: "file://./charts/account-service"

  - name: cash-service
    version: "0.1.0"
    repository: "file://./charts/cash-service"

  - name: transfer-service
    version: "0.1.0"
    repository: "file://./charts/transfer-service"

  - name: notification-service
    version: "0.1.0"
    repository: "file://./charts/notification-service"

  - name: postgresql
    version: "18.2.0"
    repository: "file://./charts/postgresql"
    alias: account-db
    condition: account-db.enabled

  - name: postgresql
    version: "18.2.0"
    repository: "file://./charts/postgresql"
    alias: cash-db
    condition: cash-db.enabled

  - name: postgresql
    version: "18.2.0"
    repository: "file://./charts/postgresql"
    alias: transfer-db
    condition: transfer-db.enabled

  - name: postgresql
    version: "18.2.0"
    repository: "file://./charts/postgresql"
    alias: notification-db
    condition: notification-db.enabled

  - name: kafka
    version: "25.0.0"
    repository: "file://./charts/kafka"
    condition: kafka.enabled

  - name: debezium-operator
    version: "3.2.0-final"
    repository: "file://./charts/debezium-operator"
    condition: debezium-operator.enabled
