global:
  domain: bank.local

  keycloak:
    issuerUri: "http://bank-keycloak:9002/realms/bank-realm"

account-service:
  replicaCount: 1
  image:
    repository: bank-platform-microservices-account-service
    tag: "latest"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 9005
  ingress:
    enabled: true
    className: "nginx"
    hosts:
      - host: account.bank.local
        paths:
          - path: /
            pathType: ImplementationSpecific
  # Database connection details passed to account-service configmap
  config:
    database_url: "jdbc:postgresql://{{ .Release.Name }}-account-db:5432/accounts"
    database_username: "account_user"
    database_password_secret: "bank-account-db-secret"
    database_password_secret_key: "password"

cash-service:
  replicaCount: 1
  image:
    repository: bank-platform-microservices-cash-service
    tag: "latest"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 9004
  ingress:
    enabled: true
    className: "nginx"
    hosts:
      - host: cash.bank.local
        paths:
          - path: /
            pathType: ImplementationSpecific
  config:
    database_url: "jdbc:postgresql://{{ .Release.Name }}-cash-db:5432/cashes"
    database_username: "cash_user"
    database_password_secret: "bank-cash-db-secret"
    database_password_secret_key: "password"

transfer-service:
  replicaCount: 1
  image:
    repository: bank-platform-microservices-transfer-service
    tag: "latest"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 9003
  ingress:
    enabled: true
    className: "nginx"
    hosts:
      - host: transfer.bank.local
        paths:
          - path: /
            pathType: ImplementationSpecific
  config:
    database_url: "jdbc:postgresql://{{ .Release.Name }}-transfer-db:5432/transfers"
    database_username: "transfer_user"
    database_password_secret: "bank-transfer-db-secret"
    database_password_secret_key: "password"

notification-service:
  replicaCount: 1
  image:
    repository: bank-platform-microservices-notification-service
    tag: "latest"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 9006
  ingress:
    enabled: true
    className: "nginx"
    hosts:
      - host: notification.bank.local
        paths:
          - path: /
            pathType: ImplementationSpecific
  config:
    database_url: "jdbc:postgresql://{{ .Release.Name }}-notification-db:5432/notifications"
    database_username: "notification_user"
    database_password_secret: "bank-notification-db-secret"
    database_password_secret_key: "password"

account-db:
  enabled: true
  auth:
    database: accounts
    username: account_user
    existingSecret: bank-account-db-secret
  primary:
    persistence:
      enabled: true
      size: 1Gi

cash-db:
  enabled: true
  auth:
    database: cashes
    username: cash_user
    existingSecret: bank-cash-db-secret
  primary:
    persistence:
      enabled: true
      size: 1Gi

transfer-db:
  enabled: true
  auth:
    database: transfers
    username: transfer_user
    existingSecret: bank-transfer-db-secret
  primary:
    persistence:
      enabled: true
      size: 1Gi
    configuration: |
      wal_level = logical
      listen_addresses = '*'
      port = 5432
  initdbScripts:
   create-replication-user.sql: |
      CREATE USER debezium WITH REPLICATION LOGIN PASSWORD 'debezium';
      GRANT SELECT ON ALL TABLES IN SCHEMA public TO debezium;

notification-db:
  enabled: true
  auth:
    database: notifications
    username: notification_user
    existingSecret: bank-notification-db-secret
  primary:
    persistence:
      enabled: true
      size: 1Gi

keycloak:
  external:
    enabled: true
    serviceName: bank-keycloak
    serviceType: ClusterIP
    port: 9002
    targetPort: 9002
    hostIP: "192.168.10.197"
    # hostname: "keycloak.bank.local"
    annotations: {}

kafka:
  enabled: true

  controller:
    replicaCount: 1
  broker:
    replicaCount: 1

  image:
    registry: docker.io
    repository: bitnamilegacy/kafka
    tag: 3.5.1-debian-11-r25

  kraft:
    enabled: true
    clusterId: "5Lx7d9n6Qr2Rv5x8Yz3wXA"

  listeners:
    client:
      protocol: PLAINTEXT
      containerPort: 9092
    controller:
      protocol: PLAINTEXT
      containerPort: 9093

  advertisedListeners: "PLAINTEXT://bank-kafka:9092"

  persistence:
    enabled: true
    size: 10Gi

  zookeeper:
    enabled: false

  volumePermissions:
    enabled: false

keycloak-external:
  enabled: true
  externalIP: 10.42.0.1  # IP хоста для Rancher Desktop
  service:
    name: bank-keycloak
    port: 9002

debezium-operator:
  enabled: true

  server:
    enabled: true

  replicaCount: 1

  image:
    repository: quay.io/debezium/operator
    tag: "3.2.0.Final"
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 8080

  config:
    BOOTSTRAP_SERVERS: "bank-kafka:9092"
    GROUP_ID: "1"
    CONFIG_STORAGE_TOPIC: "connect_configs"
    OFFSET_STORAGE_TOPIC: "connect_offsets"
    STATUS_STORAGE_TOPIC: "connect_statuses"
    KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
    VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
    KEY_CONVERTER_SCHEMAS_ENABLE: "false"
    VALUE_CONVERTER_SCHEMAS_ENABLE: "false"
  connectors:
    transfer-outbox:
      enabled: true
      name: "transfer-outbox-connector"
      config:
        connector.class: "io.debezium.connector.postgresql.PostgresConnector"
        database.hostname: "bank-transfer-db"
        database.port: "5432"
        database.user: "postgres"
        database.password: "postgres"
        database.dbname: "transfers"
        topic.prefix: "transfer"
        table.include.list: "public.transfer_outbox"
        plugin.name: "pgoutput"
        publication.name: "dbz_publication"
        slot.name: "outbox_slot"
  resources:
    limits:
      memory: 1Gi
      cpu: 500m
    requests:
      memory: 512Mi
      cpu: 250m
  persistence:
    enabled: true
    size: 1Gi